// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNrYfa-Fr_iFFtiNKP8Fit27ZuO75JeIM',
    appId: '1:649534744462:web:0e2e684141a8383bbda6df',
    messagingSenderId: '649534744462',
    projectId: 'attendx24-1f890',
    authDomain: 'attendx24-1f890.firebaseapp.com',
    storageBucket: 'attendx24-1f890.firebasestorage.app',
    measurementId: 'G-XN0V8MQLW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwTfAyrpw6_XGohsm2xuidkk4BZeLI2EI',
    appId: '1:649534744462:android:a81f6c6796e6fba6bda6df',
    messagingSenderId: '649534744462',
    projectId: 'attendx24-1f890',
    storageBucket: 'attendx24-1f890.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO4s9qTYPLIxpDHwVYcbwRn0LF4xnkfcw',
    appId: '1:649534744462:ios:02b9caa48e7b35e3bda6df',
    messagingSenderId: '649534744462',
    projectId: 'attendx24-1f890',
    storageBucket: 'attendx24-1f890.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO4s9qTYPLIxpDHwVYcbwRn0LF4xnkfcw',
    appId: '1:649534744462:ios:02b9caa48e7b35e3bda6df',
    messagingSenderId: '649534744462',
    projectId: 'attendx24-1f890',
    storageBucket: 'attendx24-1f890.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNrYfa-Fr_iFFtiNKP8Fit27ZuO75JeIM',
    appId: '1:649534744462:web:7c7ec68428c99c83bda6df',
    messagingSenderId: '649534744462',
    projectId: 'attendx24-1f890',
    authDomain: 'attendx24-1f890.firebaseapp.com',
    storageBucket: 'attendx24-1f890.firebasestorage.app',
    measurementId: 'G-L8MKQY0JFQ',
  );
}
